source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

platform :ios, '9.0'

target 'MLLogin_Example' do
  pod 'MLLogin', :path => '../'
  
#  pod 'LookinServer' , :configurations => ['Debug']

  target 'MLLogin_Tests' do
    inherit! :search_paths

  end
end
